### PR TITLE
Add support for directories outside of tenant route

### PR DESCRIPTION
**Pull request by subdiox**
## Idea
I added support for directories outside of the tenant route (e.g. `[site]`) to make it more flexible when developing a multi-tenant site.

### Sample directory structure
```
pages
├── @
│   └── index.vue
├── [site]
│   ├── index.vue
│   └── search.vue
└── admin
    ├── dashboard.vue
    └── login.vue
```

### Actual Routing
- `userA.example.com`
  - `/`: `pages/[site]/index.vue` with `site = "userA"`
  - `/search`: `pages/[site]/search.vue` with `site = "userA"`
- `admin.example.com`
  - `/login`: `pages/admin/login.vue`
  - `/dashboard`: `pages/admin/dashboard.vue`
- `example.com`
  - `/`: `pages/@/index.vue`

## Developer Tests
- Tested that the sample directory structure shown above and checked it shows the routing shown in Actual Routing section.

### CODE REVIEW

**Comment by subdiox** [comment]
I noticed that vue files placed in `pages` directory are ignored. Let me consider this PR again.

**Comment by subdiox** [comment]
`@` is used to indicate that it is a root domain. This might be a fundamental change of this library, so I'm absolutely okay if you reject my proposal.

**Comment by hieuhani** [comment]
@subdiox thanks for the PR, I see this is a good to have feature, so I would want to spend sometime to learn more about the convention. To me I want to keep the root path, and the its sub directories belong to the root domain.
For example:
root-site.com/admin
root-site.com/my_profile
...

So that reason why I have to add the `tenantDynamicRoute` to the config to explicitly set.

So what do you think about explicitly config sub-domains for what we want to?

**Comment by hieuhani** [comment]
Hi @subdiox,
Because I don't want other developers need to break their folder structure.
I would want to propose this approach:
We config the list of **static directories** to be serving by sub-domains:

Static site:
admin.example.com
analytics.example.com
id.example.com
Dynamic sites:
siteA.example.com
siteB.example.com


```js
export default defineNuxtConfig({
  modules: ['nuxt-multi-tenancy'],
  // default options
  multiTenancy: {
    tenantDynamicRoute: 'site',
    rootDomains: ["example.com"],
    sites: ["admin", "analytics", "id"]
  },
})
```


the pages directory will be:
```
pages
├── [site]
 │   ├── index.vue
 │   └── search.vue
└── admin
    ├── dashboard.vue
    └── login.vue
└── analytics
    ├── index.vue
└── id
    ├── forgot-password.vue
    └── login.vue
```

**Comment by subdiox** [comment]
@hieuhani 
Of course I understand your idea of not breaking the other developers' websites, but it still feels a bit strange for me.
Let's see if we want to make a website with the following config:
```typescript
export default defineNuxtConfig({
  modules: ['nuxt-multi-tenancy'],
  // default options
  multiTenancy: {
    tenantDynamicRoute: 'site',
    rootDomains: ["example.com"],
    sites: ["admin"]
  },
})
```
And if you want to make both `example.com/admin/manager` and `admin.example.com/login`, you won't be able to implement it with your idea, because we cannot create directories with the same name.
```
pages
├── [site]
│   ├── index.vue
│   └── search.vue
└── admin
│   ├── index.vue
│   └── manager.vue
└── admin
    ├── dashboard.vue
    └── login.vue
```
I think we have two options:
- Closing this PR and handling this issue `won't fix`
- Create a next major version and add `Breaking change` to version changes

Both are okay for me. Actually, I created another npm module named (nuxt-multi-tenancy-plus)[https://www.npmjs.com/package/nuxt-multi-tenancy-plus), which is created based on the first idea of mine.

**Pull request closed without merging**
